In [1]:
%pip install torch torchvision transformers matplotlib

   ---------------------------------------- 0.0/203.0 MB ? eta -:--:--
   ---------------------------------------- 2.4/203.0 MB 13.4 MB/s eta 0:00:15
   - -------------------------------------- 5.5/203.0 MB 17.7 MB/s eta 0:00:12
   -- ------------------------------------- 11.3/203.0 MB 20.1 MB/s eta 0:00:10
   -- ------------------------------------- 12.1/203.0 MB 17.1 MB/s eta 0:00:12
   ---- ----------------------------------- 21.0/203.0 MB 20.7 MB/s eta 0:00:09
   ----- ---------------------------------- 26.7/203.0 MB 21.7 MB/s eta 0:00:09
   ------ --------------------------------- 31.7/203.0 MB 22.1 MB/s eta 0:00:08
   ------- -------------------------------- 36.4/203.0 MB 22.3 MB/s eta 0:00:08
   -------- ------------------------------- 42.2/203.0 MB 23.1 MB/s eta 0:00:07
   --------- ------------------------------ 48.2/203.0 MB 23.4 MB/s eta 0:00:07
   ---------- ----------------------------- 54.3/203.0 MB 23.8 MB/s eta 0:00:07
   ----------- ---------------------------- 60.0/20

In [2]:
%pip install openai-clip

     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     ---------------------------------------- 1.4/1.4 MB 17.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Using cached ftfy-6.3.1-py3-none-any.whl (44 kB)
  Created wheel for openai-clip: filename=openai_clip-1.0.1-py3-none-any.whl size=1368609 sha256=033d12f2f8fc292ae30f515f5f650e8066f03e8f01dd5ce73aabea6537bdee66
  Stored in directory: c:\users\verma\appdata\local\pip\cache\wheels\ab\49\bc\c2342e8e14878210ba4825cf314a53f2570f6fb18b91fce3cf
Successfully built openai-clip
Note: you may need to restart the kernel to use updated packages.


In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import numpy as np

# Load saved embeddings and labels
test_data = np.load(r"D:\SML Project\SML_Dataset\data\CLIP\test_embeddings.npz")
test_embeddings = test_data['embeddings']
test_labels = test_data['labels']

train_data = np.load(train_embeddings_path)
train_embeddings = train_data['embeddings']
train_labels = train_data['labels']

# Train a simple Logistic Regression classifier
print("Training Logistic Regression classifier...")
classifier = LogisticRegression(max_iter=1000, random_state=42)
classifier.fit(train_embeddings, train_labels)

# Predict sentiments on test embeddings
print("Testing the classifier on test data...")
predicted_labels = classifier.predict(test_embeddings)

# Calculate evaluation metrics
accuracy = accuracy_score(test_labels, predicted_labels)
precision = precision_score(test_labels, predicted_labels, average='weighted')  # Weighted for class imbalance
recall = recall_score(test_labels, predicted_labels, average='weighted')
f1 = f1_score(test_labels, predicted_labels, average='weighted')
conf_matrix = confusion_matrix(test_labels, predicted_labels)

print("Evaluation Results:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_report(test_labels, predicted_labels, target_names=label_mapping.keys()))


Training Logistic Regression classifier...
Testing the classifier on test data...
Evaluation Results:
Accuracy: 0.8508
Precision: 0.8519
Recall: 0.8508
F1-Score: 0.8502

Confusion Matrix:
[[1237   53   53]
 [ 123 1107  113]
 [ 125  134 1084]]

Classification Report:
              precision    recall  f1-score   support

       happy       0.83      0.92      0.87      1343
         sad       0.86      0.82      0.84      1343
       anger       0.87      0.81      0.84      1343

    accuracy                           0.85      4029
   macro avg       0.85      0.85      0.85      4029
weighted avg       0.85      0.85      0.85      4029



In [8]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import joblib

# Load CLIP embeddings
train_data = np.load("D:/SML Project/SML_Dataset/data/CLIP/train_embeddings.npz")
test_data = np.load("D:/SML Project/SML_Dataset/data/CLIP/test_embeddings.npz")

train_embeddings = train_data["embeddings"]
train_labels = train_data["labels"]

test_embeddings = test_data["embeddings"]
test_labels = test_data["labels"]

# Train Logistic Regression
clip_classifier = LogisticRegression(max_iter=1000, random_state=42)
clip_classifier.fit(train_embeddings, train_labels)

# Evaluate CLIP classifier
test_preds = clip_classifier.predict(test_embeddings)
accuracy = accuracy_score(test_labels, test_preds)
print(f"CLIP Classifier Accuracy: {accuracy:.4f}")

# Save the trained classifier
joblib.dump(clip_classifier, "D:/SML Project/SML_Dataset/data/CLIP/trained_clip_model.pkl")


CLIP Classifier Accuracy: 0.8508


['D:/SML Project/SML_Dataset/data/CLIP/trained_clip_model.pkl']

In [10]:
!pip install sentence-transformers

In [12]:
!pip install ipywidgets



usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab
labextension labhub migrate nbconvert notebook qtconsole run script server
troubleshoot trust

Jupyter command `jupyter-nbextension` not found.


In [14]:
!pip install git+https://github.com/openai/CLIP.git


  Cloning https://github.com/openai/CLIP.git to c:\users\verma\appdata\local\temp\pip-req-build-ubk9jgzp
  Resolved https://github.com/openai/CLIP.git to commit dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369570 sha256=5efd191a4d9f6a1da46bc6d6aceedd5dbf91792001fef2a7e6b8b5c161affee7
  Stored in directory: C:\Users\verma\AppData\Local\Temp\pip-ephem-wheel-cache-vmycat7l\wheels\35\3e\df\3d24cbfb3b6a06f17a2bfd7d1138900d4365d9028aa8f6e92f
Successfully built clip


  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\verma\AppData\Local\Temp\pip-req-build-ubk9jgzp'


In [19]:
import os
import torch
import clip
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import torch.nn as nn
import torch.optim as optim

# Device setup
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the CLIP model
clip_model, preprocess = clip.load("ViT-B/32", device=device)

# Image transformations (CLIP preprocess pipeline)
transform = preprocess


class ImageDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        """
        Args:
            root_dir (str): Path to dataset containing subfolders for each sentiment.
            transform (callable, optional): Transform to apply to images.
        """
        self.image_paths = []
        self.labels = []
        self.transform = transform

        # Fixed label mapping
        self.label_mapping = {'happy': 0, 'sad': 1, 'anger': 2}

        # Read image paths and labels
        for label in os.listdir(root_dir):
            label_dir = os.path.join(root_dir, label)
            if os.path.isdir(label_dir):
                for image_file in os.listdir(label_dir):
                    self.image_paths.append(os.path.join(label_dir, image_file))
                    self.labels.append(self.label_mapping[label])

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        image_path = self.image_paths[idx]
        label = self.labels[idx]

        # Load and preprocess the image
        image = Image.open(image_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        return image, label


class CLIPSentimentModel(nn.Module):
    def __init__(self, clip_embedding_dim, hidden_dim, num_classes):
        super(CLIPSentimentModel, self).__init__()
        self.fc = nn.Sequential(
            nn.Linear(clip_embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        return self.fc(x)


def train_clip_model(train_loader, test_loader, num_classes=3, num_epochs=10, lr=1e-4):
    model = CLIPSentimentModel(clip_embedding_dim=512, hidden_dim=256, num_classes=num_classes).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0.0
        correct = 0
        total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            # Extract CLIP image embeddings
            with torch.no_grad():
                image_features = clip_model.encode_image(images)

            # Forward pass
            outputs = model(image_features)
            loss = criterion(outputs, labels)

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Metrics
            total_loss += loss.item()
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        train_accuracy = correct / total
        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {total_loss / len(train_loader):.4f}, Accuracy: {train_accuracy:.4f}")

        # Validate the model
        validate_clip_model(model, test_loader, num_classes)

    # Save the trained model
    torch.save(model.state_dict(), "D:/SML Project/SML_Dataset/data/CLIP/clip_sentiment_model.pth")
    print("Model saved as clip_sentiment_model.pth")


def validate_clip_model(model, test_loader, num_classes=3):
    model.eval()
    correct = 0
    total = 0
    class_correct = [0] * num_classes
    class_total = [0] * num_classes

    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)

            # Extract CLIP image embeddings
            image_features = clip_model.encode_image(images)

            # Forward pass
            outputs = model(image_features)
            _, preds = torch.max(outputs, 1)

            correct += (preds == labels).sum().item()
            total += labels.size(0)

            for i in range(len(labels)):
                label = labels[i].item()
                class_total[label] += 1
                if preds[i] == labels[i]:
                    class_correct[label] += 1

    # Overall accuracy
    accuracy = correct / total
    print(f"Overall Test Accuracy: {accuracy:.4f}")

    # Per-class accuracy
    for i in range(num_classes):
        if class_total[i] > 0:
            print(f"Class {i} Accuracy ({['happy', 'sad', 'anger'][i]}): {class_correct[i] / class_total[i]:.4f}")
        else:
            print(f"Class {i} has no samples.")


if __name__ == "__main__":
    train_dir = r'D:\SML Project\SML_Dataset\data\train'
    test_dir = r'D:\SML Project\SML_Dataset\data\test'

    train_dataset = ImageDataset(train_dir, transform=transform)
    test_dataset = ImageDataset(test_dir, transform=transform)

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

    train_clip_model(train_loader, test_loader, num_classes=3, num_epochs=10, lr=1e-4)


Epoch 1/10, Loss: 0.4797, Accuracy: 0.8481
Overall Test Accuracy: 0.8819
Class 0 Accuracy (happy): 0.9255
Class 1 Accuracy (sad): 0.9025
Class 2 Accuracy (anger): 0.8176
Epoch 2/10, Loss: 0.2820, Accuracy: 0.9047
Overall Test Accuracy: 0.8781
Class 0 Accuracy (happy): 0.9367
Class 1 Accuracy (sad): 0.8950
Class 2 Accuracy (anger): 0.8027
Epoch 3/10, Loss: 0.2505, Accuracy: 0.9142
Overall Test Accuracy: 0.8719
Class 0 Accuracy (happy): 0.9419
Class 1 Accuracy (sad): 0.8392
Class 2 Accuracy (anger): 0.8347
Epoch 4/10, Loss: 0.2306, Accuracy: 0.9218
Overall Test Accuracy: 0.8761
Class 0 Accuracy (happy): 0.9375
Class 1 Accuracy (sad): 0.8608
Class 2 Accuracy (anger): 0.8302
Epoch 5/10, Loss: 0.2132, Accuracy: 0.9277
Overall Test Accuracy: 0.8766
Class 0 Accuracy (happy): 0.9375
Class 1 Accuracy (sad): 0.8809
Class 2 Accuracy (anger): 0.8116
Epoch 6/10, Loss: 0.1985, Accuracy: 0.9331
Overall Test Accuracy: 0.8667
Class 0 Accuracy (happy): 0.9382
Class 1 Accuracy (sad): 0.8206
Class 2 Accur